<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><RollForward>LatestMajor</RollForward><ImplicitUsings>disable</ImplicitUsings></PropertyGroup>
  <ItemGroup><Compile Include="../../Core/UI/ModsButtonPatch.cs" Link="ModsButtonPatch.cs" /></ItemGroup>
</Project>
