<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>disable</ImplicitUsings></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Core/GuardianClassInfoPatch.cs" />
    <Compile Include="../../Core/GuardianEquipmentDescription.cs" />
    <Compile Include="../../Core/GuardianEquipmentBonuses.cs" />
  </ItemGroup>
</Project>
