<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><RollForward>Major</RollForward></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../Core/LoreStoreUnlock.cs" Link="LoreStoreUnlock.cs" />
    <PackageReference Include="HarmonyX" Version="2.7.0" />
  </ItemGroup>
</Project>
