using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using System.Reflection.Emit;
using HarmonyLib;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.Profiling;
using Newtonsoft.Json.Linq;
namespace FtkResourcePrototype {
public partial class Plugin {
 static Plugin portraitProbe;
 static Texture2D TrackPortrait(int w,int h,TextureFormat f,bool mip,bool linear){Texture2D t=new Texture2D(w,h,f,mip,linear);if(portraitProbe!=null)portraitProbe.portraitCreated.Add(t);return t;}
 static IEnumerable<CodeInstruction> TrackAllocation(IEnumerable<CodeInstruction> input){int found=0;foreach(CodeInstruction c in input){if(c.opcode==OpCodes.Newobj && Equals(c.operand,typeof(Texture2D).GetConstructor(new[]{typeof(int),typeof(int),typeof(TextureFormat),typeof(bool),typeof(bool)}))){c.opcode=OpCodes.Call;c.operand=typeof(Plugin).GetMethod("TrackPortrait",BindingFlags.NonPublic|BindingFlags.Static);found++;}yield return c;}if(found!=1)throw new Exception("Expected original portrait allocation");}
 JObject PortraitTrack(){portraitProbe=this;new Harmony("com.ftkmf.portrait-allocation-probe").Patch(AccessTools.Method(typeof(uiEnemyEncounterPortrait),"Initialize",new[]{typeof(string)}),null,null,new HarmonyMethod(typeof(Plugin).GetMethod("TrackAllocation",BindingFlags.NonPublic|BindingFlags.Static)));return new JObject{{"tracking",true}};}
 uiEnemyEncounterPortrait portraitFixture; HashSet<int> portraitBefore;List<Texture2D> portraitCreated=new List<Texture2D>();
 static long drainTotal,drainMax,drainCalls;static bool drainTimerInstalled;
 static void DrainBefore(out long __state){__state=System.Diagnostics.Stopwatch.GetTimestamp();}
 static void DrainAfter(long __state){long ticks=System.Diagnostics.Stopwatch.GetTimestamp()-__state;drainTotal+=ticks;drainCalls++;if(ticks>drainMax)drainMax=ticks;}
 JObject PortraitDrainStats(){if(!drainTimerInstalled){Assembly core=null;foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies())if(a.GetName().Name=="FTKModFramework")core=a;MethodInfo method=core.GetType("FTKModFramework.Core.UI.EncounterPortraitTextures",true).GetMethod("Drain",BindingFlags.NonPublic|BindingFlags.Static);new Harmony("com.ftkmf.portrait-drain-timer").Patch(method,new HarmonyMethod(typeof(Plugin).GetMethod("DrainBefore",BindingFlags.Static|BindingFlags.NonPublic)),new HarmonyMethod(typeof(Plugin).GetMethod("DrainAfter",BindingFlags.Static|BindingFlags.NonPublic)));drainTimerInstalled=true;}JObject r=new JObject{{"calls",drainCalls},{"totalMs",drainTotal*1000.0/System.Diagnostics.Stopwatch.Frequency},{"maxMs",drainMax*1000.0/System.Diagnostics.Stopwatch.Frequency}};drainTotal=drainMax=drainCalls=0;return r;}
 JObject PortraitMode(bool enabled){if(portraitFixture!=null)throw new Exception("Destroy prior fixture before toggling");if(enabled)throw new Exception("Restart for enabled candidate");Assembly core=null;foreach(Assembly a in AppDomain.CurrentDomain.GetAssemblies())if(a.GetName().Name=="FTKModFramework")core=a;Type type=core.GetType("FTKModFramework.Core.UI.UnknownEncounterPortraitAllocationPatch",true);MethodInfo patch=type.GetMethod("Transpiler",BindingFlags.NonPublic|BindingFlags.Static);new Harmony("com.ftkmf.portrait-control").Unpatch(AccessTools.Method(typeof(uiEnemyEncounterPortrait),"Initialize",new[]{typeof(string)}),patch);return new JObject{{"enabled",false}};}

 JObject PortraitCreate(){if(portraitFixture!=null)throw new Exception("Fixture exists");portraitCreated.Clear();portraitBefore=new HashSet<int>();foreach(Texture2D t in Resources.FindObjectsOfTypeAll<Texture2D>())portraitBefore.Add(t.GetInstanceID());
 GameObject go=new GameObject("ResourcePortraitFixture",typeof(RectTransform));go.SetActive(false);portraitFixture=go.AddComponent<uiEnemyEncounterPortrait>();GameObject target=new GameObject("PortraitTarget",typeof(RectTransform));target.transform.SetParent(go.transform);portraitFixture.m_PortraitTarget=target.transform;GameObject level=new GameObject("Level",typeof(RectTransform));level.transform.SetParent(go.transform);portraitFixture.m_EnemyLevelParent=level;portraitFixture.m_EnemyLevel=level.AddComponent<Text>();return PortraitState();}
 JObject PortraitRun(string enemy,int count){if(portraitFixture==null||count<1||count>100)throw new Exception("Invalid fixture run");long before=Profiler.GetTotalAllocatedMemoryLong();var timer=System.Diagnostics.Stopwatch.StartNew();for(int i=0;i<count;i++){portraitFixture.gameObject.SetActive(false);portraitFixture.Initialize(enemy);}timer.Stop();JObject r=PortraitState();r["count"]=count;r["enemy"]=enemy;r["milliseconds"]=timer.Elapsed.TotalMilliseconds;r["allocatedBefore"]=before;r["allocatedAfter"]=Profiler.GetTotalAllocatedMemoryLong();return r;}
 JObject PortraitPlayer(){if(portraitFixture==null)throw new Exception("Missing fixture");CharacterOverworld cow=null;foreach(CharacterOverworld candidate in FTKHub.Instance.m_CharacterOverworlds)if(candidate!=null){cow=candidate;break;}if(cow==null)throw new Exception("No player");
 // Resolve the exact player ID from the installed public field at runtime.
 FieldInfo field=typeof(CharacterOverworld).GetField("m_FTKPlayerID");if(field==null)throw new Exception("Player ID field unavailable");portraitFixture.Initialize((FTKPlayerID)field.GetValue(cow));return PortraitState();}
 JObject PortraitState(){if(portraitProbe==null)foreach(Texture2D candidate in Resources.FindObjectsOfTypeAll<Texture2D>())if(!portraitBefore.Contains(candidate.GetInstanceID()) && candidate.width==328 && candidate.height==280 && candidate.format==TextureFormat.ARGB32 && !portraitCreated.Contains(candidate))portraitCreated.Add(candidate);JArray rows=new JArray();foreach(Texture2D t in portraitCreated)rows.Add(t==null?new JObject{{"destroyed",true}}:new JObject{{"destroyed",false},{"id",t.GetInstanceID()},{"width",t.width},{"height",t.height},{"format",t.format.ToString()},{"mips",t.mipmapCount}});
 JObject result=new JObject{{"widgetAlive",portraitFixture!=null},{"newTextures",rows},{"unityAllocated",Profiler.GetTotalAllocatedMemoryLong()}};
 if(portraitFixture!=null){var p=(uiActiveTimePortrait)typeof(uiEnemyEncounterPortrait).GetField("m_Portrait",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(portraitFixture);if(p!=null){Texture texture=p.m_RawImage.texture;Texture2D pixels=texture as Texture2D;if(pixels!=null && portraitBefore!=null && !portraitBefore.Contains(pixels.GetInstanceID()) && !portraitCreated.Contains(pixels))portraitCreated.Add(pixels);result["primaryTextureId"]=texture==null?0:texture.GetInstanceID();result["aliasesMatch"]=p.m_HudRawImage.texture==texture;result["sharedUnknown"]=texture==FTKUI.Instance.m_EncounterUnknown.texture;if(texture!=null)result["gpuSha256"]=GpuHash(texture);}}
 return result;}
 JObject PortraitDestroy(){if(portraitFixture!=null)Destroy(portraitFixture.gameObject);return new JObject{{"destroyRequested",true}};}
 JObject PortraitCleanupBaseline(){if(portraitProbe!=this)throw new Exception("Only tracked baseline allocations may be cleaned up");if(portraitFixture!=null)throw new Exception("Destroy fixture first");int count=0;foreach(Texture2D t in portraitCreated)if(t!=null){bool used=false;foreach(RawImage r in Resources.FindObjectsOfTypeAll<RawImage>())if(r.texture==t)used=true;foreach(OffscreenCamera c in Resources.FindObjectsOfTypeAll<OffscreenCamera>())if(c.m_Texture2D==t)used=true;if(!used){Destroy(t);count++;}}return new JObject{{"removedUnreferencedFixtureTextures",count}};}
}}
