using System;using Newtonsoft.Json.Linq;
class Program
{
static int count;static void Check(bool b){count++;if(!b)throw new Exception("assertion "+count);}static void Reject(Action a){try{a();}catch(InvalidOperationException){count++;return;}throw new Exception("expected rejection "+count);}
static JObject Cel(bool clone){return JObject.Parse(clone?@"{'celId':4,'ownerId':2,'leaseId':9,'applied':true,'acquired':true,'visualResourcesOnlyFieldPresent':true,'visualResourcesOnly':true,'targetIds':[12],'renderers':[{'rendererPath':'fishA01','rendererId':12,'meshId':100,'boneSignature':'rig','boneIds':[22],'expectedCustomMesh':true,'meshInLease':true,'targetMember':true,'materials':[{'id':200,'mainTextureId':300,'materialInLease':true,'mainTextureInLease':true}]}],'lease':{'present':true,'references':2,'registeredOwnerIds':[1,2],'currentResourceIds':[100,200,300]}}":@"{'celId':3,'ownerId':1,'leaseId':9,'applied':true,'acquired':true,'visualResourcesOnlyFieldPresent':true,'visualResourcesOnly':true,'targetIds':[11],'renderers':[{'rendererPath':'fishA01','rendererId':11,'meshId':100,'boneSignature':'rig','boneIds':[21],'expectedCustomMesh':true,'meshInLease':true,'targetMember':true,'materials':[{'id':200,'mainTextureId':300,'materialInLease':true,'mainTextureInLease':true}]}],'lease':{'present':true,'references':1,'registeredOwnerIds':[1],'currentResourceIds':[100,200,300]}}");}
static JObject Record(){return new JObject{{"bindingKind","legacy-singular"},{"sourceBeforeClone",Cel(false)},{"cloneBeforeRender",Cel(true)},{"requestedHudTexture",new JObject{{"instanceId",88}}},{"currentHudTexture",new JObject{{"instanceId",88}}}};}
static JObject StaticCel(bool clone){return JObject.Parse(clone?@"{'celId':14,'ownerId':12,'leaseId':19,'applied':true,'acquired':true,'visualResourcesOnlyFieldPresent':true,'visualResourcesOnly':false,'targetIds':[32],'renderers':[{'rendererPath':'Root_M/base/body/neck/eye/kraken2_eye','rendererKind':'MeshRenderer','rendererId':32,'meshFilterId':42,'meshId':1000,'boneSignature':null,'boneIds':[],'expectedCustomMesh':true,'meshInLease':true,'targetMember':true,'materials':[{'id':2000,'mainTextureId':3000,'materialInLease':true,'mainTextureInLease':true}]}],'lease':{'present':true,'references':2,'registeredOwnerIds':[11,12],'currentResourceIds':[1000,2000,3000]}}":@"{'celId':13,'ownerId':11,'leaseId':19,'applied':true,'acquired':true,'visualResourcesOnlyFieldPresent':true,'visualResourcesOnly':false,'targetIds':[31],'renderers':[{'rendererPath':'Root_M/base/body/neck/eye/kraken2_eye','rendererKind':'MeshRenderer','rendererId':31,'meshFilterId':41,'meshId':1000,'boneSignature':null,'boneIds':[],'expectedCustomMesh':true,'meshInLease':true,'targetMember':true,'materials':[{'id':2000,'mainTextureId':3000,'materialInLease':true,'mainTextureInLease':true}]}],'lease':{'present':true,'references':1,'registeredOwnerIds':[11],'currentResourceIds':[1000,2000,3000]}}");}
static JObject StaticRecord(){return new JObject{{"bindingKind","explicit-plural"},{"sourceBeforeClone",StaticCel(false)},{"cloneBeforeRender",StaticCel(true)},{"requestedHudTexture",new JObject{{"instanceId",88}}},{"currentHudTexture",new JObject{{"instanceId",88}}}};}
static JObject Reg(){return JObject.Parse(@"{'bindingKind':'legacy-singular','tint':[0.8,0.7,0.6,1],'scale':1,'widthBoost':1,'hunchDegrees':0,'legacyAbsoluteScale':false,'applyWetSkin':false,'hideWeapon':false,'explicitAssignmentCount':0,'glbMesh':'body.glb','glbTexture':'body.png','proceduralBody':false,'addLantern':false,'swampAura':false,'meshBundle':null,'meshName':null,'meshTextureName':null}");}
static JObject Profile(){return JObject.Parse(@"{'bindingKind':'legacy-singular','tint':[0.8,0.7,0.6,1],'renderers':[{'rendererPath':'fishA01','glbFile':'body.glb','textureFile':'body.png'}]}");}
static void Main(){
var r=Record();EnemyLifetimePolicy.Compare(r);Check((bool)r["assignedBodyAndMaterialsOwned"]);Check((bool)r["sourceToCloneMembershipCompared"]);
foreach(string key in new[]{"acquired","visualResourcesOnly"}){r=Record();r["cloneBeforeRender"][key]=false;Reject(()=>EnemyLifetimePolicy.Compare(r));}
foreach(string key in new[]{"ownerId","celId","leaseId"}){r=Record();r["cloneBeforeRender"][key]=key=="leaseId"?99:r["sourceBeforeClone"][key].DeepClone();Reject(()=>EnemyLifetimePolicy.Compare(r));}
r=Record();r["cloneBeforeRender"]["lease"]["references"]=3;Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["cloneBeforeRender"]["lease"]["registeredOwnerIds"]=new JArray(1,3);Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["cloneBeforeRender"]["lease"]["currentResourceIds"]=new JArray(100,200);Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["sourceBeforeClone"]["lease"]["registeredOwnerIds"]=new JArray(1,2);r["sourceBeforeClone"]["lease"]["references"]=2;Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["cloneBeforeRender"]["renderers"][0]["boneIds"]=new JArray(21);Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["cloneBeforeRender"]["targetIds"]=new JArray(11);Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["currentHudTexture"]["instanceId"]=89;Reject(()=>EnemyLifetimePolicy.Compare(r));
foreach(string key in new[]{"expectedCustomMesh","meshInLease","targetMember"}){r=Record();r["sourceBeforeClone"]["renderers"][0][key]=false;EnemyLifetimePolicy.Compare(r);Check(!(bool)r["assignedBodyAndMaterialsOwned"]);}
r=Record();r["sourceBeforeClone"]["applied"]=false;EnemyLifetimePolicy.Compare(r);Check(!(bool)r["assignedBodyAndMaterialsOwned"]);
r=Record();r["bindingKind"]="explicit-plural";Reject(()=>EnemyLifetimePolicy.Compare(r));
r=Record();r["bindingKind"]="explicit-plural";r["sourceBeforeClone"]["visualResourcesOnly"]=false;r["cloneBeforeRender"]["visualResourcesOnly"]=false;EnemyLifetimePolicy.Compare(r);Check((bool)r["assignedBodyAndMaterialsOwned"]);
r=StaticRecord();EnemyLifetimePolicy.Compare(r);Check((bool)r["assignedBodyAndMaterialsOwned"]);
r=StaticRecord();r["cloneBeforeRender"]["renderers"][0]["meshFilterId"]=41;Reject(()=>EnemyLifetimePolicy.Compare(r));
r=StaticRecord();r["cloneBeforeRender"]["renderers"][0]["rendererKind"]="SkinnedMeshRenderer";Reject(()=>EnemyLifetimePolicy.Compare(r));
var reg=Reg();EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile());Check(true);
foreach(string field in new[]{"proceduralBody","addLantern","swampAura"}){reg=Reg();reg[field]=true;Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));}
foreach(string field in new[]{"meshBundle","meshName","meshTextureName"}){reg=Reg();reg[field]="other";Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));}
reg=Reg();reg["bindingKind"]="explicit-plural";reg["explicitAssignmentCount"]=1;Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));
reg=Reg();reg["glbMesh"]="other.glb";Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));
reg=Reg();reg["glbTexture"]="other.png";Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));
var pin=new LeaseObservationPin("root","nonce","arm",new JObject{{"sha","core"}});pin.Check("root","nonce",new JObject{{"sha","core"}});Check(true);
Reject(()=>pin.Check("changed","nonce",new JObject{{"sha","core"}}));Reject(()=>pin.Check("root","newnonce",new JObject{{"sha","core"}}));Reject(()=>pin.Check("root","nonce",new JObject{{"sha","changed"}}));

reg=Reg();reg["tint"][0]=0.123;Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));
reg=Reg();reg["tint"][0]=(double)(float)0.8;EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile());Check(true);
foreach(string field in new[]{"scale","widthBoost","hunchDegrees"}){reg=Reg();reg[field]=7;Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));}
foreach(string field in new[]{"applyWetSkin","hideWeapon","legacyAbsoluteScale"}){reg=Reg();reg[field]=true;Reject(()=>EnemyLifetimePolicy.Registration("legacy-singular",reg,Profile()));}
var plural=JObject.Parse(@"{'bindingKind':'explicit-plural','renderers':[{'rendererPath':'fishA01','glbFile':'body.glb','textureFile':'body.png','disableNativeEmission':false}]}");
EnemyLifetimePolicy.Registration("explicit-plural",plural,Profile());Check(true);plural["renderers"][0]["glbFile"]="changed.glb";Reject(()=>EnemyLifetimePolicy.Registration("explicit-plural",plural,Profile()));
var last=(JObject)null;int frame=0;var history=new JArray();Check(EnemyLifetimePolicy.Record(history,ref last,ref frame,new JObject{{"disposed",false}},1,1));Check(!EnemyLifetimePolicy.Record(history,ref last,ref frame,new JObject{{"disposed",true}},2,1));Check((bool)last["disposed"]&&frame==2&&history.Count==1);Check(!(bool)history[0]["state"]["disposed"]);
bool allowed=EnemyLifetimePolicy.Attribution(true,false);Check(!allowed);Check(!EnemyLifetimePolicy.Attribution(allowed,true));Check(EnemyLifetimePolicy.Attribution(true,true));
var measured=JObject.Parse(@"{'instanceId':3,'rootWorld':[1,0,0,1],'resourceLease':{'references':1}}");var after=(JObject)measured.DeepClone();after["resourceLease"]["references"]=2;Check(EnemyLifetimePolicy.SourceUnchanged(measured,after));after["rootWorld"][0]=2;Check(!EnemyLifetimePolicy.SourceUnchanged(measured,after));Check(!EnemyLifetimePolicy.SourceUnchanged(measured,null));
bool invalid=false;int checks=0;EnemyLifetimePolicy.CheckIdentity(ref invalid,delegate{checks++;});Check(!invalid&&checks==1);Reject(()=>EnemyLifetimePolicy.CheckIdentity(ref invalid,delegate{checks++;throw new InvalidOperationException("changed file pin");}));Check(invalid&&checks==2);Reject(()=>EnemyLifetimePolicy.CheckIdentity(ref invalid,delegate{checks++;}));Check(checks==2); // Restoring a file cannot reopen the watch.
Console.WriteLine(count+" linked lifetime policy/pin assertions PASS");}}
